config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :cattabs

  resources :subcats
  resources :menus
  root 'home#index'
  resources :categories
  get 'menu/:id/categories'=>"home#menu_category",:as=>"menu_cat"
  get 'categories/:id/subcats'=>"home#cat_subcat",:as=>"cat_subcat"
  get 'menu/categories/new/:id'=>"categories#new",:as=>"add_cat_menu"
  get 'categories/subcats/new/:id'=>"subcats#new",:as=>"add_cat_subcat" 
  get "subcats/cattabs/new/:id"=>"cattabs#new",:as=>"add_subcat_cattabs"
  get 'subcats/:id/cattabs'=>"home#subcat_tabs",:as=>"subcat_tabs"

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  has_many :category
  mount_uploader :image, ImageUploader
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]
  before_filter :sign_in_check
  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end
    def sign_in_check
      if not user_signed_in?
        redirect_to new_user_session_path
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:name, :desc, :visible,:image)
    end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :visible %><br>
    <%= f.check_box :visible %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', :back %>

app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Menus</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th>Visible</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.name %></td>
        <td><%= menu.desc %></td>
        <td><%= menu.visible %></td>
        <td><%=menu.image%></td>
        <td><%=link_to "Add category",add_cat_menu_path(menu)%></td>
        <td><%= link_to 'Show', menu %></td>
        <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @menu.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @menu.desc %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @menu.visible %>
</p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', :back %>