config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :cattabs

  resources :subcats
  resources :menus
  root 'home#index'
  resources :categories
  get 'menu/:id/categories'=>"home#menu_category",:as=>"menu_cat"
  get 'categories/:id/subcats'=>"home#cat_subcat",:as=>"cat_subcat"
  get 'menu/categories/new/:id'=>"categories#new",:as=>"add_cat_menu"
  get 'categories/subcats/new/:id'=>"subcats#new",:as=>"add_cat_subcat" 
  get "subcats/cattabs/new/:id"=>"cattabs#new",:as=>"add_subcat_cattabs"
  get 'subcats/:id/cattabs'=>"home#subcat_tabs",:as=>"subcat_tabs"

end

app/models/cattab.rb
class Cattab < ActiveRecord::Base
  belongs_to :subcat
end

app/controllers/cattabs_controller.rb
class CattabsController < ApplicationController
  before_action :set_cattab, only: [:show, :edit, :update, :destroy]

  # GET /cattabs
  # GET /cattabs.json
  def index
    @cattabs = Cattab.all
  end

  # GET /cattabs/1
  # GET /cattabs/1.json
  def show
  end

  # GET /cattabs/new
  def new
    @@subcat_cat_id=params[:id]
    @cattab = Cattab.new
  end

  # GET /cattabs/1/edit
  def edit
  end

  # POST /cattabs
  # POST /cattabs.json
  def create
    @cattab = Cattab.new(cattab_params)
    @cattab.subcat_id=@@subcat_cat_id
    respond_to do |format|
      if @cattab.save
        format.html { redirect_to @cattab, notice: 'Cattab was successfully created.' }
        format.json { render :show, status: :created, location: @cattab }
      else
        format.html { render :new }
        format.json { render json: @cattab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cattabs/1
  # PATCH/PUT /cattabs/1.json
  def update
    respond_to do |format|
      if @cattab.update(cattab_params)
        format.html { redirect_to @cattab, notice: 'Cattab was successfully updated.' }
        format.json { render :show, status: :ok, location: @cattab }
      else
        format.html { render :edit }
        format.json { render json: @cattab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cattabs/1
  # DELETE /cattabs/1.json
  def destroy
    @cattab.destroy
    respond_to do |format|
      format.html { redirect_to cattabs_url, notice: 'Cattab was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cattab
      @cattab = Cattab.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cattab_params
      params.require(:cattab).permit(:name,:content,:subcat_id)
    end
end

app/helpers/cattabs_helper.rb
module CattabsHelper
end

app/views/cattabs/_form.html.erb
<%= form_for(@cattab) do |f| %>
  <% if @cattab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cattab.errors.count, "error") %> prohibited this cattab from being saved:</h2>

      <ul>
      <% @cattab.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div>
    <%= f.label :subcat_id %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cattabs/edit.html.erb
<h1>Editing Cattab</h1>

<%= render 'form' %>

<%= link_to 'Show', @cattab %> |
<%= link_to 'Back', cattabs_path %>

app/views/cattabs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cattabs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th>Content</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cattabs.each do |cattab| %>
      <tr>
        <td><%= cattab.name %></td>
        <td><%= cattab.content %></td>
        <td><%= link_to 'Show', cattab %></td>
        <td><%= link_to 'Edit', edit_cattab_path(cattab) %></td>
        <td><%= link_to 'Destroy', cattab, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cattab', new_cattab_path %>

app/views/cattabs/new.html.erb
<h1>New Cattab</h1>

<%= render 'form' %>

<%= link_to 'Back', cattabs_path %>

app/views/cattabs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cattab.name %>
</p>


<p>
  <strong>Content:</strong>
  <%= @cattab.content %>
</p>


<%= link_to 'Edit', edit_cattab_path(@cattab) %> |
<%= link_to 'Back', cattabs_path %>