config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :cattabs

  resources :subcats
  resources :menus
  root 'home#index'
  resources :categories
  get 'menu/:id/categories'=>"home#menu_category",:as=>"menu_cat"
  get 'categories/:id/subcats'=>"home#cat_subcat",:as=>"cat_subcat"
  get 'menu/categories/new/:id'=>"categories#new",:as=>"add_cat_menu"
  get 'categories/subcats/new/:id'=>"subcats#new",:as=>"add_cat_subcat" 
  get "subcats/cattabs/new/:id"=>"cattabs#new",:as=>"add_subcat_cattabs"
  get 'subcats/:id/cattabs'=>"home#subcat_tabs",:as=>"subcat_tabs"

end

app/models/subcat.rb
class Subcat < ActiveRecord::Base
  belongs_to :category
  has_many :cattab
  mount_uploader :image,ImageUploader
end

app/controllers/subcats_controller.rb
class SubcatsController < ApplicationController
  before_action :set_subcat, only: [:show, :edit, :update, :destroy]
 before_filter :sign_in_check
  # GET /subcats
  # GET /subcats.json
  def index
    @subcats = Subcat.all
  end

  # GET /subcats/1
  # GET /subcats/1.json
  def show
  end

  # GET /subcats/new
  def new
    if params[:id].nil?
      flash[:danger]="No direct access"
      redirect_to root_path
    else
      @@cat_subcat_id=params[:id]
      @subcat = Subcat.new
    end
  end

  # GET /subcats/1/edit
  def edit
  end

  # POST /subcats
  # POST /subcats.json
  def create
    @subcat = Subcat.new(subcat_params)
    @subcat.category_id=@@cat_subcat_id
    respond_to do |format|
      if @subcat.save
        format.html { redirect_to @subcat, notice: 'Subcat was successfully created.' }
        format.json { render :show, status: :created, location: @subcat }
      else
        format.html { render :new }
        format.json { render json: @subcat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subcats/1
  # PATCH/PUT /subcats/1.json
  def update
    respond_to do |format|
      if @subcat.update(subcat_params)
        format.html { redirect_to @subcat, notice: 'Subcat was successfully updated.' }
        format.json { render :show, status: :ok, location: @subcat }
      else
        format.html { render :edit }
        format.json { render json: @subcat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcats/1
  # DELETE /subcats/1.json
  def destroy
    @subcat.destroy
    respond_to do |format|
      format.html { redirect_to subcats_url, notice: 'Subcat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcat
      @subcat = Subcat.find(params[:id])
    end
def sign_in_check
      if not user_signed_in?
        redirect_to new_user_session_path
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def subcat_params
      params.require(:subcat).permit(:name, :desc, :visible,:category_id,:image)
    end
end

app/helpers/subcats_helper.rb
module SubcatsHelper
end

app/views/subcats/_form.html.erb
<%= form_for(@subcat) do |f| %>
  <% if @subcat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subcat.errors.count, "error") %> prohibited this subcat from being saved:</h2>

      <ul>
      <% @subcat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :visible %><br>
    <%= f.check_box :visible %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subcats/edit.html.erb
<h1>Editing Subcat</h1>

<%= render 'form' %>

<%= link_to 'Show', @subcat %> |
<%= link_to 'Back', :back %>

app/views/subcats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subcats</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th>Visible</th>
      <th>Show tabs</th>
      <th>Add tabs</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subcats.each do |subcat| %>
      <tr>
        <td><%= subcat.name %></td>
        <td><%= subcat.desc %></td>
        <td><%= subcat.visible %></td>
        <td><%=link_to "Get tabs",subcat_tabs_path(subcat)%></td>
        <td><%=link_to "Add tabs",add_subcat_cattabs_path(subcat)%></td>
        <td><%= link_to 'Show', subcat %></td>
        <td><%= link_to 'Edit', edit_subcat_path(subcat) %></td>
        <td><%= link_to 'Destroy', subcat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subcat', new_subcat_path %>

app/views/subcats/new.html.erb
<h1>New Subcat</h1>

<%= render 'form' %>

<%= link_to 'Back', :back%>

app/views/subcats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subcat.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @subcat.desc %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @subcat.visible %>
</p>

<%= link_to 'Edit', edit_subcat_path(@subcat) %> |
<%= link_to 'Back', :back %>